ports:
  - port: 8888
    onOpen: open-preview
tasks:
  - name: install_deno
    before: | 
      curl -fsSL http://deno.land/x/install/install.sh | sh
      export DENO_INSTALL=/home/gitpod/.deno
      echo export DENO_INSTALL=/home/gitpod/.deno >> ~/.bashrc

      export PATH=$DENO_INSTALL/bin:$PATH
      echo export PATH=$DENO_INSTALL/bin:$PATH >> ~/.bashrc
    init: |
      deno upgrade    
    command: |
      deno run source/welcome.ts
      
vscode:
  extensions:
    - denoland.vscode-deno
